spring:
  application:
    name: realtime-caching-gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/realtime_caching_gateway
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.github.gseobi.cachinggateway.domain


gateway:
  redis:
    message-ttl-seconds: 600
    conversation-meta-ttl-seconds: 360
  sync:
    initial-delay-ms: 10000     # 10sec sync cycle initial delay set
    fixed-delay-ms: 180000      # 3min sync cycle set
    adjust-cron: "0 0 4 * * *"  # 4am adjust cycle set